runtime: nodejs12
env: flex
automatic scaling:
  min_num_instances: 1
  max_num_instances: 4

handlers:
- url: /.*
  script: auto
- url: /
  static_files: build/index.html
  upload: build/index.html
- url: /
  static_dir: build

# Serve all static files with url ending with a file extension
#- url: /(.*\..+)$
#  static_files: build/\1
#  upload: build/(.*\..+)$
# Catch all handler to index.html